blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussions
    url: https://github.com/alienx5499/sortvisioN/discussions
    about: Ask questions, share ideas, or discuss features with the community
  - name: ğŸ“  Contribution Guidelines
    url: https://github.com/alienx5499/sortvisioN/blob/main/CONTRIBUTING.md
    about: Read the contribution guidelines
  - name: ğŸ“š Documentation
    url: https://github.com/alienx5499/sortvisioN/blob/main/README.md
    about: Check the project documentation and setup instructions
  - name: ğŸŒ Live Demo
    url: https://sortvision.vercel.app/
    about: Try the live application to understand features and functionality 